# Generated by Django 2.2.1 on 2019-05-11 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 11, 15, 42, 20, 593018)),
        ),
    ]
